"""BODYGEN -> NOTION push. Optional downstream step for bodygen.py.

Writes generated email bodies into the SAME Notion database the composer reads
(the "Email Campaign Tracker"), using the EXACT property names, endpoint, API
version, and env var the composer uses (see composer/src/lib/notion.js):

  - Title property : 'Subject Line'   (NOT 'Subject')
  - Body           : 'Body Copy'      (composer skips rows where this is empty)
  - Preheader      : 'Preheader'
  - Category       : 'Category'        (select)
  - Send Date      : 'Send Date'       (date)
  - Status         : 'Status'          (select; composer drafts rows where = 'draft')
  - Agent Notes    : 'Agent Notes'     (rich_text; audit trail)

  Endpoint    : POST /data_sources/{NOTION_DB_ID}/query   (data-sources API)
  API version : 2025-09-03
  Env var     : NOTION_TOKEN, NOTION_DB_ID   (reuses the composer's own secrets)

Contract honored:
- Rows land with Status = 'draft'. The composer turns a draft row into a CC
  DRAFT; nothing here or there sends. The human gate is untouched.
- Idempotent WITHOUT adding any new property: matches an existing row by
  'Subject Line'. If a match exists and already has non-empty Body Copy, it's
  left alone unless overwrite=True (human edits are never clobbered). No match
  -> a new row is created with Status='draft'.

Imported only when --push-notion is passed. Fails loudly if token/db missing
so copy is never silently dropped (bodies are always in bodies/*.json anyway).
"""
from __future__ import annotations
import os
import json
import urllib.request
import urllib.error

NOTION_VERSION = "2025-09-03"        # matches composer/src/lib/notion.js
API = "https://api.notion.com/v1"

# Property names -- MUST match the composer's reader exactly.
P_SUBJECT = "Subject Line"           # title property
P_BODY = "Body Copy"
P_PREHEADER = "Preheader"
P_CATEGORY = "Category"
P_SEND_DATE = "Send Date"
P_STATUS = "Status"
P_NOTES = "Agent Notes"


def _cfg() -> tuple[str, str]:
    token = os.environ.get("NOTION_TOKEN")
    db = os.environ.get("NOTION_DB_ID")   # same var the composer uses
    if not token or not db:
        raise RuntimeError(
            "NOTION_TOKEN and NOTION_DB_ID must both be set to push to Notion. "
            "(bodies were already written to bodies/*.json regardless.)"
        )
    return token, db


def _req(method: str, path: str, token: str, payload=None) -> dict:
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(API + path, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Notion-Version", NOTION_VERSION)
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")
        raise RuntimeError(f"Notion {method} {path} -> {e.code}: {detail}") from None


def _rich(text: str) -> dict:
    return {"rich_text": [{"text": {"content": (text or "")[:1990]}}]}


def _plain(prop) -> str:
    """Read text out of a Notion title/rich_text property (composer's helper)."""
    if not prop:
        return ""
    arr = prop.get("title") or prop.get("rich_text") or []
    return "".join(seg.get("plain_text", "") for seg in arr)


def _find_by_subject(token: str, db: str, subject: str):
    """Find an existing tracker row by Subject Line via the data-sources query
    endpoint the composer uses. Returns the page or None."""
    res = _req("POST", f"/data_sources/{db}/query", token, {
        "filter": {"property": P_SUBJECT, "title": {"equals": subject}},
        "page_size": 1,
    })
    results = res.get("results", [])
    return results[0] if results else None


def _row_has_body(page: dict) -> bool:
    return bool(_plain(page.get("properties", {}).get(P_BODY)).strip())


def _properties_for(body: dict) -> dict:
    props = {
        P_SUBJECT: {"title": [{"text": {"content": (body.get("subject") or "")[:1990]}}]},
        P_BODY: _rich(body.get("body", "")),
        P_PREHEADER: _rich(body.get("preheader", "")),
        P_STATUS: {"select": {"name": "draft"}},
    }
    if body.get("category"):
        props[P_CATEGORY] = {"select": {"name": str(body["category"])[:100]}}
    if body.get("send_date"):
        props[P_SEND_DATE] = {"date": {"start": body["send_date"]}}
    note = (f"Body generated by bodygen {body.get('generated_at','')} "
            f"(posture={body.get('posture','strict')}; content_id={body.get('content_id','')}).")
    flags = body.get("compliance_flags") or []
    if flags:
        note += f" WARNING compliance flags: {', '.join(flags)} - review before send."
    props[P_NOTES] = _rich(note)
    return props


def push_one(body: dict, token: str, db: str, overwrite: bool = False) -> str:
    """Upsert a single generated body, keyed on Subject Line.
    Returns 'created' | 'updated' | 'skipped-has-body'."""
    subject = body.get("subject") or ""
    props = _properties_for(body)
    existing = _find_by_subject(token, db, subject) if subject else None

    if existing:
        if _row_has_body(existing) and not overwrite:
            return "skipped-has-body"
        _req("PATCH", f"/pages/{existing['id']}", token, {"properties": props})
        return "updated"

    _req("POST", "/pages", token,
         {"parent": {"data_source_id": db}, "properties": props})
    return "created"


def push_bodies(bodies: list, overwrite: bool = False) -> dict:
    """Push a list of generated bodies. Returns a tally dict."""
    token, db = _cfg()
    tally = {"created": 0, "updated": 0, "skipped-has-body": 0, "errors": []}
    for b in bodies:
        try:
            result = push_one(b, token, db, overwrite=overwrite)
            tally[result] = tally.get(result, 0) + 1
        except Exception as e:
            tally["errors"].append({"subject": b.get("subject"), "error": str(e)})
    return tally
